/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.produktion;

import BE.BELager;
import BE.BEProduktion;
import BLL.BLLLagerManager;
import BLL.BLLMaterialeManager;
import BLL.BLLProduktionManager;
import BLL.BLLSleeveManager;
import BLL.BLLStockItemManager;
import java.util.Date;
import java.util.Observer;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Christoffer
 */
public abstract class ProduktionForm extends javax.swing.JDialog implements Observer {

    private BLLProduktionManager promgr;
    private BLLLagerManager lagmgr;
    private BLLSleeveManager slmgr;
    private BLLStockItemManager stmgr;
    private BLLMaterialeManager mmgr;
    private ProduktionFormTableModel promodel;
    private ProduktionFormTableModel promodel2;
    private LagerTableModel lagmodel;
    private LagerTableModel lagmodel2;
    private BELager lager = null;

    /**
     * Creates new form ProduktionForm
     */
    public ProduktionForm(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        constructTables();
        selectOrder();
        centerTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpFilter = new javax.swing.ButtonGroup();
        lblIgangvaerendeProduktion = new javax.swing.JLabel();
        jscrpProdOrdre = new javax.swing.JScrollPane();
        jtblVaelgOrdre = new javax.swing.JTable();
        lblVaelgOrdre = new javax.swing.JLabel();
        jscrpVaelgOrdre = new javax.swing.JScrollPane();
        jtblSortOrdre = new javax.swing.JTable();
        btnAfbyd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmployeeNo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLager = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Belman Produktion");
        setFocusTraversalPolicyProvider(true);
        setIconImage(null);
        setMaximumSize(new java.awt.Dimension(780, 665));
        setMinimumSize(new java.awt.Dimension(780, 665));
        setName("Belman produktion"); // NOI18N

        lblIgangvaerendeProduktion.setText("Choose an order to produce");

        jtblVaelgOrdre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jscrpProdOrdre.setViewportView(jtblVaelgOrdre);

        lblVaelgOrdre.setText("Orders matching material in guillotine");

        jtblSortOrdre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jscrpVaelgOrdre.setViewportView(jtblSortOrdre);

        btnAfbyd.setText("Cancel");
        btnAfbyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfbydActionPerformed(evt);
            }
        });

        jLabel1.setText("Order job in");

        txtEmployeeNo.setText("EmployeeNo.");

        txtLength.setText("Length");

        txtWidth.setText("Width");

        txtQuantity.setText("Quantity");

        jtblLager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblLager);

        jLabel2.setText("Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(lblIgangvaerendeProduktion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jscrpProdOrdre, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jscrpVaelgOrdre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAfbyd))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtEmployeeNo)
                                    .addComponent(jSeparator1)
                                    .addComponent(txtLength)
                                    .addComponent(txtWidth)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVaelgOrdre)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jscrpProdOrdre, jscrpVaelgOrdre});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAfbyd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIgangvaerendeProduktion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrpProdOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVaelgOrdre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrpVaelgOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfbydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfbydActionPerformed
        dispose();
    }//GEN-LAST:event_btnAfbydActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProduktionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProduktionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProduktionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProduktionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProduktionForm().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfbyd;
    private javax.swing.ButtonGroup btngrpFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane jscrpProdOrdre;
    private javax.swing.JScrollPane jscrpVaelgOrdre;
    private javax.swing.JTable jtblLager;
    private javax.swing.JTable jtblSortOrdre;
    private javax.swing.JTable jtblVaelgOrdre;
    private javax.swing.JLabel lblIgangvaerendeProduktion;
    private javax.swing.JLabel lblVaelgOrdre;
    private javax.swing.JTextField txtEmployeeNo;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

    private void constructTables() throws Exception {
        initComponents();
        setLocationRelativeTo(this);


        lagmgr = new BLLLagerManager();
//        lagmodel = new GUI.produktion.LagerTableModel(lagmgr.visLager());
//        jtblLager.setModel(lagmodel);


        
        lagmgr = BLLLagerManager.getInstance();
        lagmgr.addObserver(this);
        lagmodel2 = new LagerTableModel(lagmgr.visLager());
        jtblLager.setModel(lagmodel2);

        lagmgr = BLLLagerManager.getInstance();
        lagmgr.addObserver(this);
        lagmodel2 = new LagerTableModel(lagmgr.visLager());
        jtblLager.setModel(lagmodel2);

        promgr = BLLProduktionManager.getInstance();
        promgr.addObserver(this);
        promodel2 = new ProduktionFormTableModel(promgr.visOrdrer());
        jtblVaelgOrdre.setModel(promodel2);
    }

    private void centerTables() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jtblVaelgOrdre.setDefaultRenderer(String.class, centerRenderer);
        jtblVaelgOrdre.setDefaultRenderer(Float.class, centerRenderer);
        jtblVaelgOrdre.setDefaultRenderer(int.class, centerRenderer);
        jtblVaelgOrdre.setDefaultRenderer(Date.class, centerRenderer);
        jtblSortOrdre.setDefaultRenderer(String.class, centerRenderer);
        jtblSortOrdre.setDefaultRenderer(Float.class, centerRenderer);
        jtblSortOrdre.setDefaultRenderer(int.class, centerRenderer);
        jtblSortOrdre.setDefaultRenderer(Date.class, centerRenderer);
        jtblLager.setDefaultRenderer(String.class, centerRenderer);
        jtblLager.setDefaultRenderer(Float.class, centerRenderer);
        jtblLager.setDefaultRenderer(int.class, centerRenderer);
    }

//    @Override
//    public void update(Observable o, Object arg) {
//        if (o instanceof BLLProduktionManager) {
//            try {
//                promodel.setCollection(promgr.visOrdrer());
//            } catch (Exception e) {
//            }
//        }
//    }

    private void selectOrder() {
        try {
            promgr = BLLProduktionManager.getInstance();
            promgr.addObserver(this);
            promodel = new ProduktionFormTableModel(promgr.visOrdrer());
            
            lagmgr = BLLLagerManager.getInstance();
            lagmgr.addObserver(this);
            lagmodel = new LagerTableModel(lagmgr.visLager());
            jtblVaelgOrdre.setModel(promodel);

            jtblVaelgOrdre.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent evt) {
                    int selectedRow = jtblVaelgOrdre.getSelectedRow();
                    BEProduktion p = promodel.getOrderByRow(selectedRow);
                    txtEmployeeNo.setText("" + p.getMaterialID());
                    txtWidth.setText("" + p.getWidth());
                    txtLength.setText("" + p.getWidth());
                    txtQuantity.setText("" + p.getQuantity());

                    try {
                        if (!promgr.getOrderByMaterial(p).isEmpty());
                        {
                            promodel2 = new ProduktionFormTableModel(promgr.getOrderByMaterial(p));
                            jtblSortOrdre.setModel(promodel2);
//                            jtblSortOrdre.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//                                @Override
//                                public void valueChanged(ListSelectionEvent evt) {
//                                    int selectedRow = jtblSortOrdre.getSelectedRow();
//                                    BEProduktion q = promodel2.getOrderByMaterial(selectedRow);
//                                    clearFields();
//                                    txtEmployeeNo.setText("" + q.getMaterialID());
//                                    txtWidth.setText("" + q.getWidth());
//                                    txtLength.setText("" + q.getWidth());
//                                    txtQuantity.setText("" + q.getQuantity());
//                                    
//                                }
//                            });
                        }
//                        int selectedRow = jtblVaelgOrdre.getSelectedRow();
                        BELager l = lagmodel.getMedlemByRow(selectedRow);
                        if (!lagmgr.materialeLager(l).isEmpty());
                        {
                            lagmodel2 = new LagerTableModel(lagmgr.materialeLager(l));
                            jtblLager.setModel(lagmodel2);
                        }
                    } catch (Exception e) {
                        System.out.println("ERROR - Line 337 " + e.getMessage());
                    }
                }

                private void clearFields() {
                    txtEmployeeNo.setText("");
                    txtWidth.setText("");
                    txtLength.setText("");
                    txtQuantity.setText("");
                }
            });
        } catch (Exception e) {
            System.out.println("ERROR - Line 349 " + e.getMessage());
        }
    }
}
