/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.medlem;

import BE.BEMedlem;
import BLL.BLLMedlemManager;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Stoffer
 */
public class MedlemAddForm extends javax.swing.JDialog
{
    private MedlemTableModel medmodel;
    private BEMedlem medlem = null;

    /**
     * Creates new form addMedlemForm
     */
    public MedlemAddForm(java.awt.Frame parent, boolean modal) throws SQLServerException, SQLException
    {
        super(parent, modal);
        initComponents();
        
//        medmodel = new MedlemTableModel(medmgr.visMedlemmer());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblPostNr = new javax.swing.JLabel();
        txtAddresse1 = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        lblEfterNavn = new javax.swing.JLabel();
        txtFodselsdag = new javax.swing.JTextField();
        txtNavn = new javax.swing.JTextField();
        lblFodselsdag = new javax.swing.JLabel();
        lblAddresse1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtEfterNavn = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblNavn = new javax.swing.JLabel();
        lblTlfNr = new javax.swing.JLabel();
        txtTlfNr = new javax.swing.JTextField();
        lblMobilNr = new javax.swing.JLabel();
        txtMobilNr = new javax.swing.JTextField();
        btnAfbryd = new javax.swing.JButton();
        chkKontingent = new javax.swing.JCheckBox();
        txtPostNr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Efternavn:");

        jLabel2.setText("Navn:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tilføj medlem");
        setLocationByPlatform(true);
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.POPUP);

        lblPostNr.setText("Postnr :");
        lblPostNr.setBounds(220, 70, 38, 14);
        jLayeredPane1.add(lblPostNr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtAddresse1.setBounds(120, 70, 92, 20);
        jLayeredPane1.add(txtAddresse1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        btnOk.setBounds(150, 250, 65, 23);
        jLayeredPane1.add(btnOk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblEfterNavn.setText("Efternavn:");
        lblEfterNavn.setBounds(30, 40, 70, 14);
        jLayeredPane1.add(lblEfterNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtFodselsdag.setBounds(120, 190, 200, 20);
        jLayeredPane1.add(txtFodselsdag, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtNavn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNavnActionPerformed(evt);
            }
        });
        txtNavn.setBounds(120, 10, 200, 20);
        jLayeredPane1.add(txtNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFodselsdag.setText("Fødselsdag:");
        lblFodselsdag.setBounds(20, 190, 80, 14);
        jLayeredPane1.add(lblFodselsdag, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblAddresse1.setText("Addresse:");
        lblAddresse1.setBounds(30, 70, 70, 14);
        jLayeredPane1.add(lblAddresse1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtEmail.setBounds(120, 160, 200, 20);
        jLayeredPane1.add(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtEfterNavn.setBounds(120, 40, 200, 20);
        jLayeredPane1.add(txtEfterNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblEmail.setText("Email:");
        lblEmail.setBounds(50, 160, 50, 14);
        jLayeredPane1.add(lblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblNavn.setText("Navn");
        lblNavn.setBounds(40, 10, 50, 14);
        jLayeredPane1.add(lblNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTlfNr.setText("Tlfnr:");
        lblTlfNr.setBounds(60, 110, 50, 14);
        jLayeredPane1.add(lblTlfNr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtTlfNr.setBounds(120, 100, 200, 20);
        jLayeredPane1.add(txtTlfNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMobilNr.setText("Mobilnr:");
        lblMobilNr.setBounds(40, 140, 60, 14);
        jLayeredPane1.add(lblMobilNr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtMobilNr.setBounds(120, 130, 200, 20);
        jLayeredPane1.add(txtMobilNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAfbryd.setText("Afbryd");
        btnAfbryd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfbrydActionPerformed(evt);
            }
        });
        btnAfbryd.setBounds(230, 250, 65, 23);
        jLayeredPane1.add(btnAfbryd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        chkKontingent.setText("Har betalt kontingent");
        chkKontingent.setBounds(190, 220, 127, 23);
        jLayeredPane1.add(chkKontingent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtPostNr.setBounds(260, 70, 60, 20);
        jLayeredPane1.add(txtPostNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 0, 380, 310);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfbrydActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAfbrydActionPerformed
    {//GEN-HEADEREND:event_btnAfbrydActionPerformed
        dispose();
    }//GEN-LAST:event_btnAfbrydActionPerformed

    private void txtNavnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNavnActionPerformed
    {//GEN-HEADEREND:event_txtNavnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNavnActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try
        {
            String navn = txtNavn.getText();
            String efternavn = txtEfterNavn.getText();
            String addresse = txtAddresse1.getText();
            String postnr = txtPostNr.getText();
            String tlfnr = txtTlfNr.getText();
            String mobnr = txtMobilNr.getText();
            String email = txtEmail.getText();
            String fodselsdag = txtFodselsdag.getText();
            Boolean kontingent = chkKontingent.isSelected();
        
            BEMedlem m = new BEMedlem(-1, navn, efternavn, addresse, postnr, tlfnr, mobnr, email, fodselsdag, kontingent );
            BLLMedlemManager.getInstance().addMember(m);
        }
        catch (Exception ex)
        {
            Logger.getLogger(MedlemAddForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        


    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfbryd;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox chkKontingent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAddresse1;
    private javax.swing.JLabel lblEfterNavn;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFodselsdag;
    private javax.swing.JLabel lblMobilNr;
    private javax.swing.JLabel lblNavn;
    private javax.swing.JLabel lblPostNr;
    private javax.swing.JLabel lblTlfNr;
    private javax.swing.JTextField txtAddresse1;
    private javax.swing.JTextField txtEfterNavn;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFodselsdag;
    private javax.swing.JTextField txtMobilNr;
    private javax.swing.JTextField txtNavn;
    private javax.swing.JTextField txtPostNr;
    private javax.swing.JTextField txtTlfNr;
    // End of variables declaration//GEN-END:variables
}
