/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.medlem;

import BE.BEMedlem;
import BLL.BLLMedlemManager;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Stoffer
 */
public class MedlemAddForm extends javax.swing.JDialog
{
    private MedlemTableModel medmodel;
    private BEMedlem medlem = null;

    /**
     * Creates new form addMedlemForm
     */
    public MedlemAddForm(java.awt.Frame parent, boolean modal) throws SQLServerException, SQLException
    {
        super(parent, modal);
        initComponents();
        addEnterKeyListeners();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblPostNr = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        lblEfterNavn = new javax.swing.JLabel();
        lblFodselsdag = new javax.swing.JLabel();
        lblAddresse1 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNavn = new javax.swing.JLabel();
        lblTlfNr = new javax.swing.JLabel();
        lblMobilNr = new javax.swing.JLabel();
        btnAfbryd = new javax.swing.JButton();
        chkKontingent = new javax.swing.JCheckBox();
        txtEmail = new javax.swing.JTextField();
        txtFodselsdag = new javax.swing.JTextField();
        txtEfterNavn = new javax.swing.JTextField();
        txtMobilNr = new javax.swing.JTextField();
        txtNavn = new javax.swing.JTextField();
        txtTlfNr = new javax.swing.JTextField();
        txtAddresse1 = new javax.swing.JTextField();
        txtPostNr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Efternavn:");

        jLabel2.setText("Navn:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tilføj medlem");
        setLocationByPlatform(true);
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.POPUP);

        lblPostNr.setText("Postnr :");
        lblPostNr.setBounds(190, 70, 50, 14);
        jLayeredPane1.add(lblPostNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        btnOk.setBounds(120, 270, 65, 23);
        jLayeredPane1.add(btnOk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblEfterNavn.setText("Efternavn:");
        lblEfterNavn.setBounds(20, 40, 70, 14);
        jLayeredPane1.add(lblEfterNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFodselsdag.setText("Fødselsdag:");
        lblFodselsdag.setBounds(10, 190, 80, 14);
        jLayeredPane1.add(lblFodselsdag, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblAddresse1.setText("Addresse:");
        lblAddresse1.setBounds(20, 70, 70, 14);
        jLayeredPane1.add(lblAddresse1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblEmail.setText("Email:");
        lblEmail.setBounds(40, 160, 50, 14);
        jLayeredPane1.add(lblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblNavn.setText("Navn:");
        lblNavn.setBounds(40, 10, 50, 14);
        jLayeredPane1.add(lblNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTlfNr.setText("Tlfnr:");
        lblTlfNr.setBounds(40, 100, 50, 14);
        jLayeredPane1.add(lblTlfNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMobilNr.setText("Mobilnr:");
        lblMobilNr.setBounds(30, 130, 60, 14);
        jLayeredPane1.add(lblMobilNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAfbryd.setText("Afbryd");
        btnAfbryd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfbrydActionPerformed(evt);
            }
        });
        btnAfbryd.setBounds(200, 270, 65, 23);
        jLayeredPane1.add(btnAfbryd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        chkKontingent.setText("Har betalt kontingent");
        chkKontingent.setBounds(90, 230, 160, 23);
        jLayeredPane1.add(chkKontingent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtEmail.setPreferredSize(new java.awt.Dimension(6, 25));
        txtEmail.setBounds(90, 160, 210, 25);
        jLayeredPane1.add(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtFodselsdag.setPreferredSize(new java.awt.Dimension(6, 25));
        txtFodselsdag.setBounds(90, 190, 210, 25);
        jLayeredPane1.add(txtFodselsdag, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtEfterNavn.setPreferredSize(new java.awt.Dimension(6, 25));
        txtEfterNavn.setBounds(90, 40, 210, 25);
        jLayeredPane1.add(txtEfterNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtMobilNr.setPreferredSize(new java.awt.Dimension(6, 25));
        txtMobilNr.setBounds(90, 130, 210, 25);
        jLayeredPane1.add(txtMobilNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtNavn.setPreferredSize(new java.awt.Dimension(6, 25));
        txtNavn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNavnActionPerformed(evt);
            }
        });
        txtNavn.setBounds(90, 10, 210, 25);
        jLayeredPane1.add(txtNavn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtTlfNr.setPreferredSize(new java.awt.Dimension(6, 25));
        txtTlfNr.setBounds(90, 100, 210, 25);
        jLayeredPane1.add(txtTlfNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtAddresse1.setMinimumSize(new java.awt.Dimension(6, 25));
        txtAddresse1.setPreferredSize(new java.awt.Dimension(6, 25));
        txtAddresse1.setBounds(90, 70, 92, 25);
        jLayeredPane1.add(txtAddresse1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPostNr.setMinimumSize(new java.awt.Dimension(6, 25));
        txtPostNr.setPreferredSize(new java.awt.Dimension(6, 25));
        txtPostNr.setBounds(240, 70, 60, 25);
        jLayeredPane1.add(txtPostNr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("(ÅÅÅÅ)");
        jLabel4.setBounds(20, 210, 50, 14);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 0, 320, 310);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfbrydActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAfbrydActionPerformed
    {//GEN-HEADEREND:event_btnAfbrydActionPerformed
        dispose();
    }//GEN-LAST:event_btnAfbrydActionPerformed

    private void txtNavnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNavnActionPerformed
    {//GEN-HEADEREND:event_txtNavnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNavnActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String errorMessage = validateRequiredFields();
        if ("".equals(errorMessage))
        {
            try
            {
                String navn = txtNavn.getText().trim();
                String efternavn = txtEfterNavn.getText().trim();
                String addresse = txtAddresse1.getText().trim();
                String postnr = txtPostNr.getText().trim();
                String tlfnr = txtTlfNr.getText().trim();
                String mobnr = txtMobilNr.getText().trim();
                String email = txtEmail.getText().trim();
                String fodselsdag = txtFodselsdag.getText().trim();
                Boolean kontingent = chkKontingent.isSelected();

                BEMedlem m = new BEMedlem(-1, navn, efternavn, addresse, postnr, tlfnr, mobnr, email, fodselsdag, kontingent );
                BLLMedlemManager.getInstance().addMember(m);
                JOptionPane.showMessageDialog(this, "Medlem tilføjet til databasen");
                clearFields();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
                System.out.println("ERROR" + e.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, errorMessage, getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOkActionPerformed

        
    private String validateRequiredFields()
    {
        String errorMessage = "";
        if (txtNavn == null || txtNavn.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde navn\n";
        }
        if (txtEfterNavn == null || txtEfterNavn.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde efternavn\n";
        }
        if (txtAddresse1 == null || txtAddresse1.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde addresse\n";
        }
        if (txtPostNr == null || txtPostNr.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde postnr\n";
        }
        if (txtTlfNr == null || txtTlfNr.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde tlfnr\n";
        }
        if (txtMobilNr == null || txtMobilNr.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde mobilnr\n";
        }
        if (txtEmail == null || txtEmail.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde email\n";
        }
        if (txtFodselsdag == null || txtFodselsdag.getText().trim().isEmpty())
        {
            errorMessage += "Du mangler at udfylde fødselsår\n";
        }
        return errorMessage;
    }
    
    private void clearFields()
    {
        txtNavn.setText("");
        txtEfterNavn.setText("");
        txtAddresse1.setText("");
        txtPostNr.setText("");
        txtTlfNr.setText("");
        txtMobilNr.setText("");
        txtEmail.setText("");
        txtFodselsdag.setText("");
    }
    
    private void addEnterKeyListeners()
    {
        KeyListener enterListener = new KeyAdapter()
        {
            @Override
            public void keyPressed(KeyEvent ke)
            {
                if (ke.getKeyCode() == KeyEvent.VK_ENTER)
                {
                    btnOk.doClick();
                }
            }
        };
        txtNavn.addKeyListener(enterListener);
        txtEfterNavn.addKeyListener(enterListener);
        txtAddresse1.addKeyListener(enterListener);
        txtPostNr.addKeyListener(enterListener);
        txtTlfNr.addKeyListener(enterListener);
        txtMobilNr.addKeyListener(enterListener);
        txtEmail.addKeyListener(enterListener);
        txtFodselsdag.addKeyListener(enterListener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfbryd;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox chkKontingent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAddresse1;
    private javax.swing.JLabel lblEfterNavn;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFodselsdag;
    private javax.swing.JLabel lblMobilNr;
    private javax.swing.JLabel lblNavn;
    private javax.swing.JLabel lblPostNr;
    private javax.swing.JLabel lblTlfNr;
    private javax.swing.JTextField txtAddresse1;
    private javax.swing.JTextField txtEfterNavn;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFodselsdag;
    private javax.swing.JTextField txtMobilNr;
    private javax.swing.JTextField txtNavn;
    private javax.swing.JTextField txtPostNr;
    private javax.swing.JTextField txtTlfNr;
    // End of variables declaration//GEN-END:variables
}
