/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.events.EventVisForm;
import GUI.medlem.MedlemAddForm;
import GUI.medlem.MedlemVisForm;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jrjakobsen
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnMedlemTilføj = new javax.swing.JButton();
        btnMedlemVis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddEvent = new javax.swing.JButton();
        btnVisEvent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TieBreak");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        btnMedlemTilføj.setText("Tilføj");
        btnMedlemTilføj.setMaximumSize(null);
        btnMedlemTilføj.setMinimumSize(new java.awt.Dimension(25, 0));
        btnMedlemTilføj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedlemTilføjActionPerformed(evt);
            }
        });
        btnMedlemTilføj.setBounds(80, 290, 95, 23);
        jLayeredPane1.add(btnMedlemTilføj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        btnMedlemTilføj.getAccessibleContext().setAccessibleParent(this);

        btnMedlemVis.setText("Oversigt");
        btnMedlemVis.setMinimumSize(new java.awt.Dimension(25, 0));
        btnMedlemVis.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedlemVisActionPerformed(evt);
            }
        });
        btnMedlemVis.setBounds(80, 260, 95, 23);
        jLayeredPane1.add(btnMedlemVis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Medlemmer");
        jLabel2.setBounds(90, 240, 80, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Events");
        jLabel3.setBounds(220, 240, 50, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAddEvent.setText("Tilføj");
        btnAddEvent.setBounds(200, 290, 95, 23);
        jLayeredPane1.add(btnAddEvent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnVisEvent.setText("Oversigt");
        btnVisEvent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVisEventActionPerformed(evt);
            }
        });
        btnVisEvent.setBounds(200, 260, 95, 23);
        jLayeredPane1.add(btnVisEvent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/TieBreak.jpg"))); // NOI18N
        jLabel1.setBounds(-80, -10, 620, 440);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedlemTilføjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedlemTilføjActionPerformed
        try {
            MedlemAddForm medForm = new MedlemAddForm(this, true);
//            medForm.setLocationRelativeTo(null);
            medForm.pack();
            medForm.setVisible(true);
        } catch (SQLServerException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMedlemTilføjActionPerformed

    private void btnMedlemVisActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMedlemVisActionPerformed
    {//GEN-HEADEREND:event_btnMedlemVisActionPerformed
        try
        {
            MedlemVisForm medForm = new MedlemVisForm(this, true);
//            medForm.setLocationRelativeTo(null);
            medForm.pack();
            medForm.setVisible(true);
        }
        catch (Exception ex)
        {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMedlemVisActionPerformed

    private void btnVisEventActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVisEventActionPerformed
    {//GEN-HEADEREND:event_btnVisEventActionPerformed
        try
        {
            EventVisForm evtForm = new EventVisForm(this, true);
//            evtForm.setLocationRelativeTo(null);
            evtForm.pack();
            evtForm.setVisible(true);
        }
        catch (Exception ex)
        {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVisEventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        String username =
                JOptionPane.showInputDialog("Brugernavn:");
        String password =
                JOptionPane.showInputDialog("Kodeord:");
        
        if (
                username != null &&
                password != null &&
                (
                    (username.equals("admin") &&
                    password.equals("1234"))
                )
            )
        {
            JOptionPane.showMessageDialog(null, "Du er nu logget ind.");
            new MainGUI().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Dit brugernavn eller kode er forkert.");
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnMedlemTilføj;
    private javax.swing.JButton btnMedlemVis;
    private javax.swing.JButton btnVisEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
