/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jrjakobsen
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnMedlemTilføj = new javax.swing.JButton();
        btnMedlemVis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnBookingRediger = new javax.swing.JButton();
        btnBookingFjern = new javax.swing.JButton();
        btnBookingTilføj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnHoldRediger = new javax.swing.JButton();
        btnHoldFjern = new javax.swing.JButton();
        btnHoldTilføj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TieBreak");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        btnMedlemTilføj.setText("Tilføj");
        btnMedlemTilføj.setMaximumSize(null);
        btnMedlemTilføj.setMinimumSize(new java.awt.Dimension(25, 0));
        btnMedlemTilføj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedlemTilføjActionPerformed(evt);
            }
        });
        btnMedlemTilføj.setBounds(80, 290, 95, 23);
        jLayeredPane1.add(btnMedlemTilføj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        btnMedlemTilføj.getAccessibleContext().setAccessibleParent(this);

        btnMedlemVis.setText("Oversigt");
        btnMedlemVis.setMinimumSize(new java.awt.Dimension(25, 0));
        btnMedlemVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedlemVisActionPerformed(evt);
            }
        });
        btnMedlemVis.setBounds(80, 260, 95, 23);
        jLayeredPane1.add(btnMedlemVis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Medlemmer");
        jLabel2.setBounds(90, 240, 80, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Booking");
        jLabel3.setBounds(340, 180, 56, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Oversigt");
        jButton3.setBounds(320, 200, 95, 23);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnBookingRediger.setText("Rediger");
        btnBookingRediger.setBounds(320, 230, 95, 23);
        jLayeredPane1.add(btnBookingRediger, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnBookingFjern.setText("Fjern");
        btnBookingFjern.setBounds(320, 260, 95, 23);
        jLayeredPane1.add(btnBookingFjern, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnBookingTilføj.setText("Tilføj");
        btnBookingTilføj.setBounds(320, 290, 95, 23);
        jLayeredPane1.add(btnBookingTilføj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Hold");
        jLabel4.setBounds(240, 180, 40, 14);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Oversigt");
        jButton2.setBounds(200, 200, 95, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnHoldRediger.setText("Rediger");
        btnHoldRediger.setBounds(200, 230, 95, 23);
        jLayeredPane1.add(btnHoldRediger, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnHoldFjern.setText("Fjern");
        btnHoldFjern.setBounds(200, 260, 95, 23);
        jLayeredPane1.add(btnHoldFjern, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnHoldTilføj.setText("Tilføj");
        btnHoldTilføj.setBounds(200, 290, 95, 23);
        jLayeredPane1.add(btnHoldTilføj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/TieBreak.jpg"))); // NOI18N
        jLabel1.setBounds(-90, 0, 640, 450);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedlemTilføjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedlemTilføjActionPerformed
        try {
            MedlemAddForm medForm = new MedlemAddForm(this, true);
            medForm.setLocationRelativeTo(this);
            medForm.pack();
            medForm.setVisible(true);
        } catch (SQLServerException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMedlemTilføjActionPerformed

    private void btnMedlemVisActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMedlemVisActionPerformed
    {//GEN-HEADEREND:event_btnMedlemVisActionPerformed
        try
        {
            MedlemVisForm medForm = new MedlemVisForm(this, true);
            medForm.setLocationRelativeTo(this);
            medForm.pack();
            medForm.setVisible(true);
        }
        catch (Exception ex)
        {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMedlemVisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookingFjern;
    private javax.swing.JButton btnBookingRediger;
    private javax.swing.JButton btnBookingTilføj;
    private javax.swing.JButton btnHoldFjern;
    private javax.swing.JButton btnHoldRediger;
    private javax.swing.JButton btnHoldTilføj;
    private javax.swing.JButton btnMedlemTilføj;
    private javax.swing.JButton btnMedlemVis;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
