/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Jrjakobsen
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        PanelMedlemmer = new javax.swing.JPanel();
        btnMedlemTilføj = new javax.swing.JButton();
        btnMedlemRediger = new javax.swing.JButton();
        btnMedlemFjern = new javax.swing.JButton();
        btnMedlemVis = new javax.swing.JButton();
        PanelHold = new javax.swing.JPanel();
        btnHoldTilføj = new javax.swing.JButton();
        btnHoldRediger = new javax.swing.JButton();
        btnHoldFjern = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelBooking = new javax.swing.JPanel();
        btnBookingTilføj = new javax.swing.JButton();
        btnBookingRediger = new javax.swing.JButton();
        btnBookingFjern = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TieBreak");
        setResizable(false);

        PanelMedlemmer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Medlemmer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btnMedlemTilføj.setText("Tilføj");
        btnMedlemTilføj.setMaximumSize(null);
        btnMedlemTilføj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedlemTilføjActionPerformed(evt);
            }
        });

        btnMedlemRediger.setText("Rediger");
        btnMedlemRediger.setMaximumSize(null);
        btnMedlemRediger.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedlemRedigerActionPerformed(evt);
            }
        });

        btnMedlemFjern.setText("Fjern");
        btnMedlemFjern.setMaximumSize(null);
        btnMedlemFjern.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedlemFjernActionPerformed(evt);
            }
        });

        btnMedlemVis.setText("Vis");
        btnMedlemVis.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedlemVisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMedlemmerLayout = new javax.swing.GroupLayout(PanelMedlemmer);
        PanelMedlemmer.setLayout(PanelMedlemmerLayout);
        PanelMedlemmerLayout.setHorizontalGroup(
            PanelMedlemmerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedlemmerLayout.createSequentialGroup()
                .addComponent(btnMedlemTilføj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedlemRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedlemFjern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedlemVis)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelMedlemmerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMedlemFjern, btnMedlemRediger, btnMedlemTilføj, btnMedlemVis});

        PanelMedlemmerLayout.setVerticalGroup(
            PanelMedlemmerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMedlemmerLayout.createSequentialGroup()
                .addGroup(PanelMedlemmerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedlemTilføj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedlemRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedlemFjern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedlemVis))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        PanelMedlemmerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMedlemFjern, btnMedlemRediger, btnMedlemTilføj});

        btnMedlemTilføj.getAccessibleContext().setAccessibleParent(this);

        PanelHold.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Hold", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btnHoldTilføj.setText("Tilføj");

        btnHoldRediger.setText("Rediger");

        btnHoldFjern.setText("Fjern");

        jButton2.setText("Vis");

        javax.swing.GroupLayout PanelHoldLayout = new javax.swing.GroupLayout(PanelHold);
        PanelHold.setLayout(PanelHoldLayout);
        PanelHoldLayout.setHorizontalGroup(
            PanelHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHoldLayout.createSequentialGroup()
                .addComponent(btnHoldTilføj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoldRediger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoldFjern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelHoldLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHoldFjern, btnHoldRediger, btnHoldTilføj, jButton2});

        PanelHoldLayout.setVerticalGroup(
            PanelHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHoldLayout.createSequentialGroup()
                .addGroup(PanelHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoldTilføj)
                    .addComponent(btnHoldRediger)
                    .addComponent(btnHoldFjern)
                    .addComponent(jButton2))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        PanelHoldLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHoldFjern, btnHoldRediger, btnHoldTilføj});

        PanelBooking.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Booking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btnBookingTilføj.setText("Tilføj");

        btnBookingRediger.setText("Rediger");

        btnBookingFjern.setText("Fjern");

        jButton3.setText("Vis");

        javax.swing.GroupLayout PanelBookingLayout = new javax.swing.GroupLayout(PanelBooking);
        PanelBooking.setLayout(PanelBookingLayout);
        PanelBookingLayout.setHorizontalGroup(
            PanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBookingLayout.createSequentialGroup()
                .addComponent(btnBookingTilføj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBookingRediger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBookingFjern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelBookingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBookingFjern, btnBookingRediger, btnBookingTilføj, jButton3});

        PanelBookingLayout.setVerticalGroup(
            PanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBookingLayout.createSequentialGroup()
                .addGroup(PanelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookingTilføj)
                    .addComponent(btnBookingRediger)
                    .addComponent(btnBookingFjern)
                    .addComponent(jButton3))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        PanelBookingLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBookingFjern, btnBookingRediger, btnBookingTilføj});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMedlemmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelHold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(PanelMedlemmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PanelBooking, PanelHold, PanelMedlemmer});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedlemTilføjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedlemTilføjActionPerformed
        MedlemAddForm medForm = new MedlemAddForm(this, true);
        medForm.setLocationRelativeTo(this);
        medForm.pack();
        medForm.setVisible(true);
    }//GEN-LAST:event_btnMedlemTilføjActionPerformed

    private void btnMedlemRedigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedlemRedigerActionPerformed
        MedlemRedigerForm medForm = new MedlemRedigerForm(this, true);
        medForm.setLocationRelativeTo(this);
        medForm.pack();
        medForm.setVisible(true);
    }//GEN-LAST:event_btnMedlemRedigerActionPerformed

    private void btnMedlemFjernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedlemFjernActionPerformed
        MedlemFjernForm medForm = new MedlemFjernForm(this, true);
        medForm.setLocationRelativeTo(this);
        medForm.pack();
        medForm.setVisible(true);
    }//GEN-LAST:event_btnMedlemFjernActionPerformed

    private void btnMedlemVisActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMedlemVisActionPerformed
    {//GEN-HEADEREND:event_btnMedlemVisActionPerformed
        MedlemVisForm medForm = new MedlemVisForm(this, true);
        medForm.setLocationRelativeTo(this);
        medForm.pack();
        medForm.setVisible(true);
    }//GEN-LAST:event_btnMedlemVisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBooking;
    private javax.swing.JPanel PanelHold;
    private javax.swing.JPanel PanelMedlemmer;
    private javax.swing.JButton btnBookingFjern;
    private javax.swing.JButton btnBookingRediger;
    private javax.swing.JButton btnBookingTilføj;
    private javax.swing.JButton btnHoldFjern;
    private javax.swing.JButton btnHoldRediger;
    private javax.swing.JButton btnHoldTilføj;
    private javax.swing.JButton btnMedlemFjern;
    private javax.swing.JButton btnMedlemRediger;
    private javax.swing.JButton btnMedlemTilføj;
    private javax.swing.JButton btnMedlemVis;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
