/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.BEMedlem;
import BLL.BLLMedlemManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Stoffer
 */
public class MedlemVisForm extends javax.swing.JDialog
{
    private BLLMedlemManager medmgr;
    private MedlemTableModel medmodel;
//    private BEMedlem medlem = null;

    /**
     * Creates new form GUIMedlemDialog
     */
    public MedlemVisForm(java.awt.Frame parent, boolean modal) throws Exception
    {
        super(parent, modal);
        initComponents();
        
        // disable update and remove buttons
        btnOpdater.setEnabled(false);
        btnFjern.setEnabled(false);
        
        // Reference for the BLL layer.
        medmgr = new BLLMedlemManager();
        
        // Set the table model for the JTable
        medmodel = new MedlemTableModel(medmgr.visMedlemmer());
        tblMedlem.setModel(medmodel);
        
        // ADD A LISTSELECTIONLISTENER TO THE SELECTIONMODEL OF THE JTABLE HERRE
        tblMedlem.getSelectionModel().addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent evt)
            {
               if (!evt.getValueIsAdjusting())
                {
                    visMedlemDetaljer();
                }
            }

            private void visMedlemDetaljer()
            {
                // Does the selection work correctly here?
                BEMedlem e = medmodel.getMedlemByRow(tblMedlem.getSelectedRow());

                txtId.setText("" + e.getId());
                txtName.setText(e.getNavn());
                txtEfternavn.setText(e.getEfternavn());
                chkKontingent.setSelected(e.harBetalt());

                btnUpdateEmployee.setEnabled(true);
                btnRemoveEmployee.setEnabled(true);
                    }
                });
            }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAfbryd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedlem = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblMedlemsNr = new javax.swing.JLabel();
        txtMedlemsNr = new javax.swing.JTextField();
        lblNavn = new javax.swing.JLabel();
        txtNavn = new javax.swing.JTextField();
        lblEfternavn = new javax.swing.JLabel();
        txtEfternavn = new javax.swing.JTextField();
        chkKontingent = new javax.swing.JCheckBox();
        btnOpdater = new javax.swing.JButton();
        btnFjern = new javax.swing.JButton();

        jLabel3.setText("Efternavn:");

        jLabel2.setText("Navn:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vis medlem");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(288, 279));
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        btnAfbryd.setText("Afbryd");
        btnAfbryd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAfbrydActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tblMedlem);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Detaljer om Medlemmet")));

        lblMedlemsNr.setText("MedlemsNr:");

        txtMedlemsNr.setEditable(false);

        lblNavn.setText("Navn:");

        lblEfternavn.setText("Efternavn:");

        chkKontingent.setText("Har betalt kontingent");

        btnOpdater.setText("Opdater medlem");

        btnFjern.setText("Fjern medlem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedlemsNr)
                            .addComponent(lblNavn)
                            .addComponent(lblEfternavn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkKontingent)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNavn)
                                .addComponent(txtMedlemsNr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEfternavn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpdater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFjern)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFjern, btnOpdater});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedlemsNr)
                    .addComponent(txtMedlemsNr))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNavn)
                    .addComponent(txtNavn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternavn)
                    .addComponent(txtEfternavn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkKontingent)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpdater)
                    .addComponent(btnFjern))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAfbryd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfbryd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Detaljer om Medlemmet");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfbrydActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAfbrydActionPerformed
    {//GEN-HEADEREND:event_btnAfbrydActionPerformed
        dispose();
    }//GEN-LAST:event_btnAfbrydActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfbryd;
    private javax.swing.JButton btnFjern;
    private javax.swing.JButton btnOpdater;
    private javax.swing.JButton btnRemoveEmployee;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JCheckBox chkKontingent;
    private javax.swing.JCheckBox chkQualified;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEfternavn;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMedlemsNr;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNavn;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JPanel panelEmployeeDetails;
    private javax.swing.JTable tblMedlem;
    private javax.swing.JTextField txtEfternavn;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMedlemsNr;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNavn;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
