/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.events;

import BE.BEEvent;
import BE.BEMedlem;
import BLL.BLLEventManager;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Stoffer
 */
public class EventVisForm extends javax.swing.JDialog
{

    private BLLEventManager evtmgr;
    private EventTableModel evtmodel;
    private BEMedlem medlem = null;

    /**
     * Creates new form GUIMedlemDialog
     */
    public EventVisForm(java.awt.Frame parent, boolean modal) throws Exception
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        // Reference for the BLL layer.
        evtmgr = new BLLEventManager();
        
        // Set the table model for the JTable
        evtmodel = new EventTableModel(evtmgr.visEvents());
        tblEvent.setModel(evtmodel);
        
        btnOpdater.setEnabled(false);
        btnFjern.setEnabled(false);
//        btnTilmeld.setEnabled(false);
        
        // ADD A LISTSELECTIONLISTENER TO THE SELECTIONMODEL OF THE JTABLE HERRE
        tblEvent.getSelectionModel().addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent evt)
            {
               if (!evt.getValueIsAdjusting())
                {
                    visMedlemDetaljer();
                }
            }

            private void visMedlemDetaljer()
                {
                // Does the selection work correctly here?
                BEEvent e = evtmodel.getEventByRow(tblEvent.getSelectedRow());
                
                jtxtBeskrivelse.setText(e.getArrangementbeskrivelse());              

                btnOpdater.setEnabled(true);
                btnFjern.setEnabled(true);
//                btnTilmeld.setEnabled(true);
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jscrEvent = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtBeskrivelse = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFjern = new javax.swing.JButton();
        btnAfbryd = new javax.swing.JButton();
        btnOpdater = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        jscrEvent.setViewportView(tblEvent);

        jscrEvent.setBounds(20, 50, 230, 130);
        jLayeredPane1.add(jscrEvent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(jtxtBeskrivelse);

        jScrollPane1.setBounds(270, 50, 330, 130);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Arrangements Beskrivelse");
        jLabel1.setBounds(280, 30, 270, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Vælg et arrangement fra listen");
        jLabel2.setBounds(20, 30, 170, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnFjern.setText("Fjern");
        btnFjern.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFjernActionPerformed(evt);
            }
        });
        btnFjern.setBounds(620, 90, 73, 23);
        jLayeredPane1.add(btnFjern, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAfbryd.setText("Afbryd");
        btnAfbryd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAfbrydActionPerformed(evt);
            }
        });
        btnAfbryd.setBounds(620, 180, 73, 23);
        jLayeredPane1.add(btnAfbryd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnOpdater.setText("Opdater");
        btnOpdater.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpdaterActionPerformed(evt);
            }
        });
        btnOpdater.setBounds(620, 50, 73, 23);
        jLayeredPane1.add(btnOpdater, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/bg.jpg"))); // NOI18N
        lblImg.setText("jLabel1");
        lblImg.setBounds(0, 0, 710, 410);
        jLayeredPane1.add(lblImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfbrydActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAfbrydActionPerformed
    {//GEN-HEADEREND:event_btnAfbrydActionPerformed
        dispose();
    }//GEN-LAST:event_btnAfbrydActionPerformed

    private void btnOpdaterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpdaterActionPerformed
    {//GEN-HEADEREND:event_btnOpdaterActionPerformed
        try
        {
            BEEvent e = evtmodel.getEventByRow(tblEvent.getSelectedRow());
            int id = e.getId();
            String arrangementbeskrivelse = jtxtBeskrivelse.getText();
            
            BEEvent m = new BEEvent(id, arrangementbeskrivelse);
            BLLEventManager.getInstance().updateEvent(m);
            JOptionPane.showMessageDialog(this, "Arrangementsbeskrivelse opdateret");
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
            System.out.println("ERROR - " + ex.getMessage());
        }
    }//GEN-LAST:event_btnOpdaterActionPerformed

    private void btnFjernActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFjernActionPerformed
    {//GEN-HEADEREND:event_btnFjernActionPerformed
        try
        {
            BEEvent e = evtmodel.getEventByRow(tblEvent.getSelectedRow());
            int id = e.getId();
            BLLEventManager.getInstance().deleteEvent(id);
            JOptionPane.showMessageDialog(this, "Event fjernet");
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
            System.out.println("ERROR - " + ex.getMessage());
        }
    }//GEN-LAST:event_btnFjernActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        }
//        catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(EventVisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(EventVisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(EventVisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(EventVisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new EventVisForm().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfbryd;
    private javax.swing.JButton btnFjern;
    private javax.swing.JButton btnOpdater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jscrEvent;
    private javax.swing.JTextPane jtxtBeskrivelse;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTable tblEvent;
    // End of variables declaration//GEN-END:variables
}
